url: https://artsitoya.com
baseurl: ""

# Site settings
title: Arts Itoya
email: info@artsitoya.com
description: "Arts Itoya is an artist in residence program in Takeo, Saga Prefecture, Japan. Studio Kura, the company in charge of the long running residence progam in Fukuoka Prefecture, started it in 2018 after reforming an old kimono shop called Itoya."


# Team names, titles and social links
people:
- name: Shim Woo Chan
  pic: 6
  position: Artist in Residence Coordinator
  social:
    - title: facebook
      url: https://www.facebook.com/woochan.shim.73


- name: Hirofumi Matsuzaki
  pic: 4
  position: Founder
  social:
    - title: facebook
      url: https://www.facebook.com/hirofumi.matsuzaki


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/ARTS-ITOYA-1660717754022412/

# Postal address (add as many lines as necessary)
address:
  - line: 7271 Takeochō Ōaza Takeo,
  - line: Takeo-shi, Saga-ken 843-0022

# Build settings
markdown: kramdown
permalink: pretty